Create a new project test
NikitaDunyashenko/Qase_Diploma pull request #2
Opened 2023-02-24 13:54 UTC by NikitaDunyashenko

2023-02-24 19:50 UTC, voropa requested changes

2023-02-24 19:50 UTC, voropa commented on src/test/java/elements/Select.java
> +    public void chooseAccessType(String type) {
Почему метод строка-локатор называются AccessType? Это же класс- декоратор select, значит оп логике он может использоваться не только для AccessType

2023-02-24 19:50 UTC, voropa commented on src/test/java/pages/HomePage.java
> +    private final static By USER_ICON = By.cssSelector(".Eb2vGG");
Плохой локатор, выглядит ненадежно

2023-02-24 19:50 UTC, voropa commented on src/test/java/tests/ProjectTests.java
> +    private final int idNumber = faker.number().numberBetween(1, 1000);
Это же тоже константа, почему тогда не в UPPER_CASE название

2023-02-25 09:09 UTC, NikitaDunyashenko commented on src/test/java/elements/Select.java
> +    public void chooseAccessType(String type) {
Исправлено

2023-02-25 09:09 UTC, NikitaDunyashenko commented on src/test/java/pages/HomePage.java
> +    private final static By USER_ICON = By.cssSelector(".Eb2vGG");
Исправлено

2023-02-25 09:10 UTC, NikitaDunyashenko commented on src/test/java/tests/ProjectTests.java
> +    private final int idNumber = faker.number().numberBetween(1, 1000);
Исправлено

2023-02-25 12:29 UTC, voropa requested changes

2023-02-25 12:29 UTC, voropa commented on src/test/java/pages/HomePage.java
> +    private final static By USER_ICON = By.cssSelector("img[alt='Nikita Dunyashenko']");
Так еще хуже) Он же не будет работать, если, например, я запущу тесты на своем аккаунте.
Я бы сделал как-то так:
//span[@aria-label="Chat"]/following-sibling::span/img

2023-02-25 12:47 UTC, NikitaDunyashenko commented on src/test/java/pages/HomePage.java
> +    private final static By USER_ICON = By.cssSelector("img[alt='Nikita Dunyashenko']");
Я понял. Забываю, что тесты не только я собираюсь запускать со своего аккаунта

2023-02-25 12:50 UTC, NikitaDunyashenko commented on src/test/java/pages/HomePage.java
> +    private final static By USER_ICON = By.cssSelector("img[alt='Nikita Dunyashenko']");
Теперь все готово

2023-02-25 12:51 UTC, voropa approved these changes

2023-02-25 12:56 UTC, merged