searching and suites tests
NikitaDunyashenko/Qase_Diploma pull request #3
Opened 2023-02-28 22:30 UTC by NikitaDunyashenko

Некоторые решения получились нестандартными, поэтому спрашивайте, если вдруг будут вопросы по коду. Смогу объяснить, почему именно так сделал

2023-03-01 07:35 UTC, voropa requested changes

2023-03-01 07:35 UTC, voropa commented on src/test/java/modals/SuiteDetailsModal.java
> +        log.info(String.format("getting locator of the following tagname: %s", tagName));
При логировании, как раз нужно писать debug() логи для таких технических методов по формированию локаторов, а info() логи для каких-то действий типе get / set value, а у вас в этом классе наоборот сделано

2023-03-01 07:35 UTC, voropa commented on src/test/java/pages/ProjectsPage.java
> +        refreshThePage();
А зачем в этих методах refreshPage() после того как сделали search?

2023-03-01 07:35 UTC, voropa commented on src/test/java/pages/ProjectsPage.java
> +            if(projectNames.get(i).contains("Demo") == false){
Почему тут захардкодано название 'Demo"?

2023-03-01 07:35 UTC, voropa commented on src/test/java/pages/ProjectsPage.java
> +            projectNames.add(text);
Зачем вам тут projectNames массив, вы же его фактически не испольщуете? Можно же сразу внуттри цикла for делать проверку projectResults.get(i).getText().contains("Demo") == false

2023-03-01 07:35 UTC, voropa commented on src/test/java/pages/ProjectsPage.java
> +    public int getListOfProjectsAfterSearching(String projectName) {
Название метода не совсем соотвествует тому, что он возвращает. В названии getList, а возвращает он int, а не list

2023-03-01 07:35 UTC, voropa commented on src/test/java/tests/SuiteTests.java
> +    Faker faker = new Faker();
Лучше этот обьект Faker проинициалищзировать в BaseTest один раз, чтобы не приходилось делать эьто много раз в каждом конкретном test-класее

2023-03-01 16:21 UTC, NikitaDunyashenko commented on src/test/java/modals/SuiteDetailsModal.java
> +        log.info(String.format("getting locator of the following tagname: %s", tagName));
Да, скопировал строчку кода и забыл везде поменять. Исправлю

2023-03-01 16:30 UTC, NikitaDunyashenko commented on src/test/java/pages/ProjectsPage.java
> +        refreshThePage();
В этом  тесте, когда я ввожу в поисковую строку название проекта, я не могу нажать на кнопку типа search, чтобы меня перекинуло на новую страницу. Там просто сами появляются проекты, соответствующие названию в search. Неявного ожидания я не придумал, какое можно поставить, чтобы тест проходил во всех случаях вне зависимости от того, какой проект ищу. Поэтому обновить страницу - единственное решение, которое нашел

2023-03-01 16:31 UTC, NikitaDunyashenko commented on src/test/java/pages/ProjectsPage.java
> +            if(projectNames.get(i).contains("Demo") == false){
Исправлю

2023-03-01 16:36 UTC, NikitaDunyashenko commented on src/test/java/pages/ProjectsPage.java
> +            projectNames.add(text);
Да, согласен. Не заметил, что у Webelement тоже можно вызвать метод contains после getText, а про стринги знал точно. Исправлю

2023-03-01 16:38 UTC, NikitaDunyashenko commented on src/test/java/pages/ProjectsPage.java
> +    public int getListOfProjectsAfterSearching(String projectName) {
Да, забыл поменять, так как когда называл метод реализация была совсем другая. Хотел взять лист стрингов и в самом тесте чтобы была проверка на contains("Назвазние проекта")

2023-03-01 16:39 UTC, NikitaDunyashenko commented on src/test/java/tests/SuiteTests.java
> +    Faker faker = new Faker();
Согласен, исправлю

2023-03-01 16:41 UTC, NikitaDunyashenko commented on src/test/java/pages/ProjectsPage.java
> +        refreshThePage();
Мне так и оставлять refreshPage? Просто долго думал, что можно кроме этого и так ни к чему и не пришел. Не исключаю, что реализовать можно красивее, но выбрал один из самых очевидных и работающих вариантов

2023-03-01 19:30 UTC, voropa commented on src/test/java/pages/ProjectsPage.java
> +        refreshThePage();
Как варинт, напишиите метод-ожиданиие, который сначала ждет пока появится этот элемент с загрузкой. а потом пропадет. Будет что-то типа:
waitForPresent(loader);
waitForNotPresent(loader);
<img width="1585" alt="image" src="https://user-images.githubusercontent.com/14195681/222244468-917af069-eb09-4fd6-9e8d-78d093338540.png">

Обычно работает в таких случаях

2023-03-02 08:37 UTC, NikitaDunyashenko commented on src/test/java/pages/ProjectsPage.java
> +        refreshThePage();
Да, все работает с этими методами

2023-03-02 10:40 UTC, voropa approved these changes

2023-03-02 11:37 UTC, merged