test-case and milestone tests + data-driven for project
NikitaDunyashenko/Qase_Diploma pull request #4
Opened 2023-03-05 15:04 UTC by NikitaDunyashenko

2023-03-05 19:36 UTC, voropa requested changes

2023-03-05 19:36 UTC, voropa commented on src/test/java/enums/Assignee.java
> +    UNASSIGNED("Unassigned"), NIKITA_DUNYASHENKO("Nikita Dunyashenko");
Enum'ы используют для статичных даннах, а тут у вас динамические данные в виде вашего аккаунта, так что неправильно заносить их в enum

2023-03-05 19:36 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    protected final static By SAVE_BUTTON = By.cssSelector("[type=submit]");
А у вас на всех страницах-наследниках BasePage есть кнопка save?

2023-03-05 19:36 UTC, voropa commented on src/test/java/pages/EditCasePage.java
> +    private final static String INPUT_LOCATOR = "//label[text()='%s']/parent::div//following-sibling::div//input";
А чего не сделали декораторы для этих элементов? Для многих других же у вас есть они

2023-03-05 19:36 UTC, voropa commented on src/test/java/pages/EditMilestonePage.java
> +    private final static String INPUT_LOCATOR = "//label[text()='%s']/parent::div//following-sibling::div//input";
И тут тоже

2023-03-06 11:56 UTC, NikitaDunyashenko commented on src/test/java/enums/Assignee.java
> +    UNASSIGNED("Unassigned"), NIKITA_DUNYASHENKO("Nikita Dunyashenko");
Да, согласен. Просто не знал, что с этим делать. Но я его вообще не использую, так как он создавался для дефекта, а я его я скорее всего через api сделаю. Так что я вообще удалю этот класс

2023-03-06 11:57 UTC, NikitaDunyashenko commented on src/test/java/pages/BasePage.java
> +    protected final static By SAVE_BUTTON = By.cssSelector("[type=submit]");
Нет, не на всех. Лучше сделать его тогда приватным и переопределять метод клика на эту кнопку в классах наследниках?

2023-03-06 12:01 UTC, NikitaDunyashenko commented on src/test/java/pages/EditCasePage.java
> +    private final static String INPUT_LOCATOR = "//label[text()='%s']/parent::div//following-sibling::div//input";
Да, я думал над декораторами для них, но не придумал название для класса, чтобы разграничивать разные декораторы для инпута, так как их несколько и непонятно, для чего в будущем я могу его приспособить и вообще смогу ли, потому что возможно этот локатор не подойдет и надо будет создавать новый декоратор, и чтобы их не плодить огромное количество, то подумал, что возможно лучше закинуть метод в класс страницы. Лучше все-таки создать декораторы?

2023-03-06 12:47 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    protected final static By SAVE_BUTTON = By.cssSelector("[type=submit]");
Нет, тут вопрос в том, что если этот элемент не находится на всех страницах-наследниках, то его не нужно помещать в BasePage. В base-классах должны быть только те свойства, которые применимы ко всем наслоедникам

2023-03-06 12:48 UTC, voropa commented on src/test/java/pages/EditCasePage.java
> +    private final static String INPUT_LOCATOR = "//label[text()='%s']/parent::div//following-sibling::div//input";
Если эти элементы у вас только на одной странице и используются один-два раза, то нет смысла создавать декораторы, можно оставиь так.

2023-03-07 19:27 UTC, voropa approved these changes

2023-03-07 20:08 UTC, merged