api-tests + RetryAnalyzer + TestListener + xml suites for running tests
NikitaDunyashenko/Qase_Diploma pull request #5
Opened 2023-03-09 12:54 UTC by NikitaDunyashenko

Тест, который фэйлится называется negativeLoginTestFailed

2023-03-09 14:01 UTC, voropa requested changes

2023-03-09 14:01 UTC, voropa commented on src/test/java/models/Defect.java
> +    public static class DefectBuilder{
А зачем вам тут public DefectBuilder, у вас же аннотация @Builder висит, Lombok за вас его создает

2023-03-09 14:01 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    public void setUp(String browserName, ITestContext testContext) {
Добавьте @Optional аннотацию для browserName, тначе не будут запускаться тесты не из консоли

2023-03-09 14:01 UTC, voropa commented on src/test/java/tests/LoginTests.java
> +    @Test(groups = {"smoke", "negative"}, retryAnalyzer = RetryAnalyzer.class)
Обьедините эти 2 теста в один data-driven

2023-03-09 14:01 UTC, voropa commented on src/test/java/tests/TestListener.java
> +        System.out.println("Test " + result.getName() + " started at" + new Date().toString());
Замените все system.out на log.info/debug

2023-03-09 14:01 UTC, voropa commented on src/test/java/tests_api/BaseApiTest.java
> +    private static final String TOKEN = "1e5c35f94b1a30f113ab2a0dbf7cf6b212e36a0ff7d8c58d12ce2a1fc2ec8491";
Вынесите BASE_URL, TOKEN в config.properties файл
а так же BASE_URL для UI тестов и логин/pass

2023-03-09 14:01 UTC, voropa commented on src/test/java/tests_api/DefectApiTests.java
> +                .post(BASE_URL + "/project")
BAS_URL у вас уже задан в глобальном сетапе restAssured. Тут нужно относительный url указывать уже: '/project'

2023-03-09 14:01 UTC, voropa commented on src/test/java/tests_api/DefectApiTests.java
> +                .body("{\"code\": \"QAFD\", \"title\": \"QASE for defects\"}")
Эти данные нужно сделать динамическими, так как второй раз такой тест уже не пройдет, проект с таким кодом уже создан будет

2023-03-09 14:01 UTC, voropa commented on src/test/java/tests_api/DefectApiTests.java
> +                .body("status", equalTo(true), "result.code", equalTo("QAFD"));
В Before/after методах не должно быть проверок, а он у вас тут есть

2023-03-09 17:45 UTC, NikitaDunyashenko commented on src/test/java/models/Defect.java
> +    public static class DefectBuilder{
IDEA ругалась. Почему-то не разрешала потом вызывать DefectBuilder, так как он не паблик по дефолту. Поэтому пришлось прописать, чтобы при компиляции он тоже был пабликом.

2023-03-09 17:46 UTC, NikitaDunyashenko commented on src/test/java/tests/BaseTest.java
> +    public void setUp(String browserName, ITestContext testContext) {
Понял, сделаю

2023-03-09 17:46 UTC, NikitaDunyashenko commented on src/test/java/tests/LoginTests.java
> +    @Test(groups = {"smoke", "negative"}, retryAnalyzer = RetryAnalyzer.class)
Исправлю

2023-03-09 17:47 UTC, NikitaDunyashenko commented on src/test/java/tests/TestListener.java
> +        System.out.println("Test " + result.getName() + " started at" + new Date().toString());
Исправлю

2023-03-09 17:49 UTC, NikitaDunyashenko commented on src/test/java/tests_api/DefectApiTests.java
> +                .body("{\"code\": \"QAFD\", \"title\": \"QASE for defects\"}")
А у меня есть afterMethod, который потом удаляет проект, поэтому сколько угодно раз может запускаться этот тест

2023-03-09 17:50 UTC, NikitaDunyashenko commented on src/test/java/tests_api/DefectApiTests.java
> +                .body("status", equalTo(true), "result.code", equalTo("QAFD"));
Даже statusCode не надо проверять?

2023-03-09 17:53 UTC, NikitaDunyashenko commented on src/test/java/models/Defect.java
> +    public static class DefectBuilder{
У меня по сути точно так же и в других моделях данных прописано. Я еще эту штуку с Salesforce помню, что IDEA ругается на вызов DefectBuilder из другого пакета (tests), где я как раз и создаю объект

2023-03-09 18:26 UTC, voropa commented on src/test/java/tests_api/DefectApiTests.java
> +                .body("status", equalTo(true), "result.code", equalTo("QAFD"));
нет, это же pre-condition, а не тест

2023-03-09 18:27 UTC, voropa commented on src/test/java/tests_api/DefectApiTests.java
> +                .body("{\"code\": \"QAFD\", \"title\": \"QASE for defects\"}")
Ок, ну тогда вынесите название и код  проекта в какие-то константы, чтобы из потом испольщовать в pre/post-conditions, а не хардкодить, как у вас сейчас сделано

2023-03-09 18:29 UTC, voropa commented on src/test/java/models/Defect.java
> +    public static class DefectBuilder{
Вот так у меня работает
<img width="691" alt="image" src="https://user-images.githubusercontent.com/14195681/224121337-8dd7c760-537f-4566-b25a-4a9c901a1e60.png">

<img width="514" alt="image" src="https://user-images.githubusercontent.com/14195681/224121364-f7a998fa-35bc-4a1b-998c-237a27f45ece.png">

2023-03-10 16:26 UTC, voropa requested changes

2023-03-10 16:26 UTC, voropa commented on src/test/java/tests_api/DefectApiTests.java
> +        Defect.DefectBuilder defectBuilder = Defect.builder()
Так можно еще  проще:
Defect defect = Defect.builder().setTitle("")...build()

2023-03-10 19:03 UTC, NikitaDunyashenko commented on src/test/java/tests_api/DefectApiTests.java
> +        Defect.DefectBuilder defectBuilder = Defect.builder()
Сделано)

2023-03-10 19:16 UTC, voropa approved these changes

2023-03-10 19:42 UTC, merged